### ISSUE TITLE
[FEATURE] Reference cards to craft the magic items with.

### ISSUE THREAD

**Issue by EthanDunning** [msprijatelj/4e-module-generator-portable-compendium#13]
If you arent aware of how magic items are created in 4e Fantasy Grounds, then feel free to watch [this video to give you an idea](https://youtu.be/NzvU0DQhZkA).

As you can see from the video, you need those grey, base cards to make the magic items. The ones that are implemented by Skeleton are technically level 0 magic items, and thus cant be used to create other magic items. If you could add a system to give each of the item modules a reference table with items in them to allow for this, that would be awesome!

**Comment by msprijatelj** [comment]
@EthanDunning I could see that being made into an update for the basic items; do you know what the module syntax is for such a table? I'm having trouble creating such a table within Fantasy Grounds itself, and can't seem to find documentation for it on their wiki.

**Comment by EthanDunning** [comment]
@msprijatelj I am sorry but I do not, but I will try to look into it myself and let you know if I find anything

**Comment by skelekon** [comment]
From the video it looks like the Armor templates are in some sort of table structure and are not true Items.

I had a look in a test 5E campaign and they seem to use a similar implementation with Magic Item templates.
They seem to work the opposite way, though with the magic effect in a template, rather than the base armor type.

I used the Universal Module extension to load the 5E SRD & 5E Magic Items SRD modules into a 4E test campaign, and the  Magic Item templates list shows up, but with no labels against the buttons - I guess it doesn't know what to do with them.
Drag and dropping them had no effect that I could trigger.

I'm happy to have a go at this, but would need some info to start from - even a single example.

Do you have any of these templates in working mod files?
If you can find one in a mod file and provide the structure that would be something to work from.

**Comment by EthanDunning** [comment]
yes I do! there should be a lot of examples in the .mod of the players handbook. I uploaded my copy [to my google drive here.](https://drive.google.com/file/d/18R5_BYgEF-_UVmYJMQ4hAEE07kq-KtxD/view?usp=sharing)/ I hope you are able to find some use for it! you are doing great work.

**Comment by skelekon** [comment]
Cheers for that.

Can confirm that the PHB item templates work with the generated magic items from the compendium to create new magic items.

Now trying to determine what is the minimum amount of xml required for a viable Template Module.
I cut too deeply on the first attempt and there was no index appearing in the Library page.

So these will apply to Weapons & Armor? Is there anything else that supports drag & drop templating? Implements maybe?
Does it check that the types or groups match or anything or does the user need to police that?

**Comment by msprijatelj** [comment]
> yes I do! there should be a lot of examples in the .mod of the players handbook. I uploaded my copy [to my google drive here.] **EDIT by @msprijatelj: Link Removed to avoid legal issues**. I hope you are able to find some use for it and get what you need! you are doing great work.

@EthanDunning I appreciate the help! I do want to warn against sharing 4E game data due to legal issues involved.  It's inconvenient for sure, but in the future if you could instead share a snippet of data-stripped XML from the mods' db.xml, it would save us some headache with regards to "what's allowed to be shared".

**Comment by msprijatelj** [comment]
> So these will apply to Weapons & Armor? Is there anything else that supports drag & drop templating? Implements maybe? Does it check that the types or groups match or anything or does the user need to police that?

Testing it out, it looks like a magic item classified as a "Weapon" will only accept weapons as a click and drag.  This is actually good for classes that use Weapliments (swordmage blades, sorcerer daggers), and doesn't matter for the other regular implements that can't be used as weapons.

**Comment by skelekon** [comment]
OK I have refactored the 4E Basic Weapons to create a Library instead of items, and can confirm it works as advertised in the video.

I will do the same for 4E Basic Armors tomorrow (it's midnight here).

I tried dropping a mundane weapon on a magic armor, and although it didn't change the name it updated the Weight - I don't know whether it is supposed to reject it entirely.

The Magic Weapons / Magic Armors scripts will need another go-around to make them work a little better with the mundane templates:
- change the Class to be Weapon / Armor to make them an invalid target for the wrong types of mundane items
- generate the actual Critical dice expression instead of e.g. 1d10 per plus

I will look at breaking out Basic Implements into the mundane library format, but I don't think there are any generic implement magic items - they all seem specific to one implement type. I guess maybe it will let you do magical versions of Superior Implements (is that allowed? I can't remember).

**Comment by msprijatelj** [comment]
@skelekon Feel free to try working with invalid mundane items, but at the end of the day I don't think it's too big of an issue if you can drag mundane equipment onto armor to make a new item.

Superior Implements is a good catch; PHB3 says that Superior Implements can be enchanted.  Breaking them out into the library makes a lot of sense; dunno if there's a meaningful difference between "Implement" and "Weapon" tags in Fantasy Grounds but in a pinch they may be coded similarly to weapons due to their keywords.

**Comment by EthanDunning** [comment]
> > yes I do! there should be a lot of examples in the .mod of the players handbook. I uploaded my copy [to my google drive here.] **EDIT by @msprijatelj: Link Removed to avoid legal issues**. I hope you are able to find some use for it and get what you need! you are doing great work.
> 
> @EthanDunning I appreciate the help! I do want to warn against sharing 4E game data due to legal issues involved. It's inconvenient for sure, but in the future if you could instead share a snippet of data-stripped XML from the mods' db.xml, it would save us some headache with regards to "what's allowed to be shared".

Okay, I will make sure to do that in the future. I do want to say that I have a bunch of 4e .mods that were gotten via direct parsing from the ddi, so if you need any books from those I can give you the snippets or whatever form you need. I know a little bit about how the mods work since I have had to go in and tweak the xml data in the past as well as create my own modules, but I do not know as much as you guys do so I will need some guidance if you require anything other than the straight mod file.

**Comment by skelekon** [comment]
If anyone has an Adventurer's Vault mod, can you check where Barding comes under?
I'm just finishing off the Armor mundane template mod and want to confirm whether to remove Barding from it.
(I'm not sure whether it needs to be made enchantable.)

Also if you have PHB3 or MME mods, can you tell me how Superior Implements are listed, and what the table seciton headings and the table columns are?

Cheers

**Comment by skelekon** [comment]
Now that Weapons, Armor & Equipment are implemented as mundane item cards for the Library, I feel like the natural next step is to make the process generic and combine them (and later other object types) into a single Library module.
So you can have e.g. 'Compendium PHB' module that contains everything player facing from the Compendium (or at least as much as is feasible).

From the work I have done so far, I can now see that there are basically three sections to each top level library item:
- the menu item that opens the table
- the table itself (the structure of which is controlled by a keyword in the menu item that points to it)
- the item cards (which again is controlled by a keyword in the table entry that points to it)

In any case, I am going to work out how to combine the three already done as that should show the path to making it modular in terms of passing around the required lists & structures.

**Comment by EthanDunning** [comment]
> Now that Weapons, Armor & Equipment are implemented as mundane item cards for the Library, I feel like the natural next step is to make the process generic and combine them (and later other object types) into a single Library module. So you can have e.g. 'Compendium PHB' module that contains everything player facing from the Compendium (or at least as much as is feasible).

Do you think you could have it be optional to have them be the way they are now, all combined? Because personally fantasy grounds sometimes unloads my players modules and it would be alot easier to only have to load the few we currently have then 10 that they get their different things from.

**Comment by skelekon** [comment]
Funny you should say that, because I have just finished implementing command line switches to control the Library details and what goes in it.
**compendium_phb** is dead - long live **module_maker**

I've renamed it and added command line parsing so that the Library name and filename can be specified (or it will default to 4E Compendium / 4E_Compendium)
Also added switches to select specific item types.

Ultimately I am wanting to add extra parameters to the existing item switches so you can specify e.g. a regex or something, so if you want to export all the weapons in the Spear group or whatever then you can (not sure why you would want to - but with something like magic items you could e.g. create separate Libraries for magic items in each Tier.

```
Usage: module_maker.py [options]

Options:
  -h, --help      show this help message and exit
  -f, --filename  create library at FILE
  -l, --library   Fantasy Grounds' internal name for the Library
  --all           include all item types in the Library (overrides other item
                  types)
  --armor         include Armor items in the Library
  --equipment     include Equipment items in the Library
  --weapons       include Weapon items in the Library

```

**Comment by skelekon** [comment]
I just completed the first cut of adding in Magic Weapons, and you're right that it becomes frozen with over 5000 magic weapons in the Library table.

I know it's possible to have sub menus that sit between the main menu and the table, but I'm not sure how they work yet.

In the meantime maybe I will split them by Tier or something - there are ~1200 Heroic tier weapons, and the table manages to work with that number without freezing up.
