### ISSUE TITLE
[BUG] HP is not shown on the combat tracker 

### ISSUE THREAD

**Issue by yagit5593** [msprijatelj/4e-module-generator-portable-compendium#19]
When you drag an NPC over to the combat tracker the HP comes up as 0.

![2022-05-14 01_23_14-Greenshot](https://user-images.githubusercontent.com/102276697/168411998-a8d8a3aa-e179-422c-a1a9-bcb87780d8ca.png)

**Comment by skelekon** [comment]
This is a bug from the original VegaFontana code - I don't know if any updates have been done to that particular code in this fork.

The issue is caused by spaces between the end of the hp open tag and the start of the hit points text.
`<hp type="string"> 82</hp>`

Should be a trivial fix to add a .strip() or similar. (Maybe line 377 of npc.py).
